### ISSUE TITLE
Unable to reproduce InternVL3.5 GPT-OSS on MMMU

### ISSUE THREAD

**Issue by johnson111788** [open-compass/VLMEvalKit#1223]
Hi,

Thanks for including InternVL3.5 in the repo. However, I tried to evaluate InternVL3_5-GPT-OSS-20B-A4B-Preview-Thinking on MMMU_DEV_VAL, and the model keeps repeating itself at the end of the response. I've attached the result from this command `python run.py --data MMMU_DEV_VAL --model InternVL3_5-GPT-OSS-20B-A4B-Preview-Thinking --verbose --reuse`. I believe there might be some template adaptation that needs to be done.

Best,
Yu-Cheng

[InternVL3_5-GPT-OSS-20B-A4B-Preview-Thinking_MMMU_DEV_VAL_openai_result.xlsx](https://github.com/user-attachments/files/22181545/InternVL3_5-GPT-OSS-20B-A4B-Preview-Thinking_MMMU_DEV_VAL_openai_result.xlsx)

**Comment by Weiyun1025** [comment]
It seems to be an issue with the xlsx format, which can only store up to 32,768 characters per cell. Therefore, when Thinking mode is activated, the output is easily truncated, and the final answer cannot be parsed. We have contacted the OpenCompass Team, and they will fix this issue as soon as possible.

**Comment by PhoenixZ810** [comment]
Thank you for taking the time to share your suggestion. We’ve addressed the issue in [PR 1294](https://github.com/open-compass/VLMEvalKit/pull/1229).
Now use  `SPLIT_THINK=True` and `PRED_FORMAT=tsv`  will lead to correct results.

**Comment by JihwanEom** [comment]
Hi @PhoenixZ810,

I’m still experiencing the repetition issue with the InternVL3.5 models in thinking mode, even after updating to the latest commit (cfa63b1df9d861313cc444af676488b6f1445222).

Here’s the setup I’m using:
```
export USE_COT=1
export SPLIT_THINK=True
export PRED_FORMAT=tsv
python3 run.py --data MMMU_DEV_VAL --model InternVL3_5-1B --verbose
python3 run.py --data MMMU_DEV_VAL --model InternVL3_5-1B-Thinking --verbose
```

Could you take another look when you get a chance? Thanks!

**Comment by PhoenixZ810** [comment]
> Hi [@PhoenixZ810](https://github.com/PhoenixZ810),
> 
> I’m still experiencing the repetition issue with the InternVL3.5 models in thinking mode, even after updating to the latest commit ([cfa63b1](https://github.com/open-compass/VLMEvalKit/commit/cfa63b1df9d861313cc444af676488b6f1445222)).
> 
> Here’s the setup I’m using:
> 
> ```
> export USE_COT=1
> export SPLIT_THINK=True
> export PRED_FORMAT=tsv
> python3 run.py --data MMMU_DEV_VAL --model InternVL3_5-1B --verbose
> python3 run.py --data MMMU_DEV_VAL --model InternVL3_5-1B-Thinking --verbose
> ```
> 
> Could you take another look when you get a chance? Thanks!

Hi, please use config `InternVL3_5-1B-Thinking` , which apply `cot_prompt_version="r1"` for MMMU benchmark.

**Comment by johnson111788** [comment]
Hi Weiyun,

Thanks for your updates. I have tried evaluting `InternVL3_5-30B-A3B-Thinking` and `InternVL3_5-GPT-OSS-20B-A4B-Preview-Thinking` using the latest commit you mentioned. However, I can only reproduce `InternVL3_5-30B-A3B-Thinking` with 75.1 accuracy on MMMU Val. **InternVL3_5-GPT-OSS-20B-A4B-Preview-Thinking only achieves 30.1 accuracy on MMMU Val**. After inspecting the response, I found three major issues: 

1. Repetition of reasoning process, causing no answer prediction. 
2. Incorrect thinking format with no `</think>` to parse the answer, causing `Match log: Z`.
3. Answering without matching options, causing `Match log: Z`.

Eventhough I remove these cases (repetition and `Match log: Z`) and only evaluate the filtered responses (396 left), `InternVL3_5-GPT-OSS-20B-A4B-Preview-Thinking` only achieves 54.0 accuracy.

<img width="1347" height="262" alt="Image" src="https://github.com/user-attachments/assets/71f13399-23e3-419b-8cce-2ad5e527c987" />

I used the following commands to run the evaluation:

```
SPLIT_THINK=True PRED_FORMAT=tsv python run.py --data MMMU_DEV_VAL --model InternVL3_5-GPT-OSS-20B-A4B-Preview-Thinking --verbose --reuse
SPLIT_THINK=True PRED_FORMAT=tsv python run.py --data MMMU_DEV_VAL --model InternVL3_5-30B-A3B-Thinking --verbose --reuse
```

Best,
Yu-Cheng

**Comment by xiaoBIGfeng** [comment]
Thanks for your great work on VLMEvalKit and the powerful InternVL models.

I've been trying to evaluate the InternVL3_5-38B model on the MMMU_DEV_VAL benchmark. I've been following the discussions in issue #1223 and have tried to use the recommended settings.

Here is the exact command I used for the evaluation:

```bash
export USE_COT=1
export SPLIT_THINK=True
export PRED_FORMAT=tsv
python3 run.py --data MMMU_DEV_VAL --model InternVL3_5-38B --verbose
```

Since my server cannot access the internet, I did not use GPT for answer verification, the final accuracy I'm getting is only 25%.

[InternVL3_5-38B-Thinking_MMMU_DEV_VAL.tsv](https://github.com/user-attachments/files/22449515/InternVL3_5-38B-Thinking_MMMU_DEV_VAL.tsv)

I am attaching the resulting CSV file which contains the detailed model predictions for your review. Could you please take a look at my setup and the results? I would be very grateful for any advice on whether there's an issue with my command, environment, or if there are other specific configurations required for the InternVL3_5-38B model to achieve the reported performance on MMMU.

Thank you for your time and help!
